#服务端口
server:
  port: 8082

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 111111
    url: jdbc:mysql://localhost:3306/artemis?characterEncoding=utf8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
  freemarker:
    allow-request-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
    template-loader-path: classpath:/ftl/
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/artemis
#      uri: mongodb://name:pass@localhost:27017/dbname


#mybatis配置
mybatis:
  mapper-locations: classpath:com/artemis/kahn/dao/mapper/*.xml
  type-aliases-package: com.artemis.kahn.dao.pojo

#seimi配置
seimi:
  crawler:
    enabled: true
    names: basic

